import type { Metadata } from "next";
import { Header } from "./components/header1";
import { Inter } from "next/font/google";
import Hero from "./components/hero";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header></Header>
        <Hero></Hero>
        {children}
      </body>
    </html>
  );
}
